Test with Java 21 and modernization
jenkinsci/pipeline-graph-analysis-plugin pull request #121
Opened 2023-10-03 07:58 UTC by gounthar

Test with Java 21
==

Java 21 was released Sep 19, 2023. We want to announce full support for Java 21 in early October and would like the most used plugins to be compiled and tested with Java 21.

The acceptance test harness and plugin bill of materials tests are already passing with Java 21. This is a further step to improve plugin readiness for use with Java 21 and for development with Java 21.

The change intentionally tests only two Java configurations, Java 17 and Java 21 because we believe that the risk of a regression that only affects Java 11 is shallow. We generate Java 11 byte code with the Java 17 and the Java 21 builds, so we're already testing Java 11 byte code.

Testing done
===

Confirmed tests pass with Java 21 after upgrading to a recent parent POM and to Jenkins version 2.361.4 as the minimum version.

2023-10-03 08:32 UTC, gounthar commented
This change is not compatible with JDK8, hence the fail.
We could replay this build while changing the content of the master Jenkinsfile with this one; that should go fine.

2023-10-03 12:14 UTC, gounthar commented
We're still using JDK8, and that's why the build is failing.
Could someone please re-run it with our proposed Jenkinsfile?
Thanks.

2023-10-03 17:40 UTC, basil commented
https://ci.jenkins.io/job/Plugins/job/pipeline-graph-analysis-plugin/job/PR-121/2/

2023-10-04 07:51 UTC, gounthar commented
Thank you, Basil. 
Unfortunately, JDK17 failed. I'll test it on my machine.

2023-10-04 08:04 UTC, gounthar commented
JDK17 works on my machine. 🤔

2023-10-08 23:52 UTC, MarkEWaite requested changes
Needs fix for plugin bom version

2023-10-08 23:52 UTC, MarkEWaite commented on pom.xml
> +        <version>4.73</version>
Optional, but nice to use most recent parent pom release.
```suggestion
        <version>4.74</version>
```

2023-10-08 23:52 UTC, MarkEWaite commented on pom.xml
> +                <version>2120.v89a_c54a_1e4f9</version>
Needs to use final release of bom-2.361.x, not an incremental
```suggestion
                <version>2102.v854b_fec19c92</version>
```

2023-10-09 09:32 UTC, gounthar commented
Thank you, Mark.

2024-02-27 19:19 UTC, jglick approved these changes

2024-02-27 20:34 UTC, merged